---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`plot.barh` permite realizar gráficos de torta"
  checked: false
- value: "`plot.pie` permite realizar gráficos de torta"
  checked: true
- value: "`value_counts` también devuelve un `Series` y por ello es posible usar su
    resultado para hacer gráficos"
  checked: true
- value: al graficar, el orden de los valores dentro de un `Series` es irrelevante
    y no tiene impacto en el gráfico resultante
  checked: false
name: Traé los pochoclos
