---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Agrupar según infracciones y calcular la media de las patentes
  checked: false
- value: Agrupar según patentes y calcular la media de las infracciones
  checked: true
- value: Agrupar según patentes y calcular la mediana de las infracciones
  checked: false
- value: Agrupar según patentes y calcular la menor de las infracciones
  checked: false
- value: Agrupar según patentes y calcular la cantidad de las infracciones
  checked: false
name: Agrupar, agrupar, cada cosa en su lugar
