---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: El nivel de empleo no varía a lo largo de los diferente años
  checked: false
- value: Las mujeres presentan siempre una menor tasa de empleo que los hombres
  checked: true
- value: Las mujeres presentan siempre una mayor tasa de empleo que los hombres
  checked: false
- value: Las mujeres presentan siempre la misma tasa de empleo que los hombres
  checked: false
- value: Las mujeres presentan a veces mayores tasas de empleo que los hombres y otras
    veces, menores
  checked: false
name: Una tabla no dice nada
